version: '2'

services:

  mirth-connect:
    build: mirth-connect
    image: jjdsp-mirth
    container_name: mc-mirthconnect
    volumes:
      - "./mirth-connect/mirth.properties:/opt/mirth-connect/conf/mirth.properties:rw"
      - "./data/spools/:/var/spool/mirth/:rw"
    ports: 
      - "13011:8080"
      - "13012:8443"
